package GUI;

import javax.swing.JFrame;

public class FullEmployeeDetailsPage extends JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public FullEmployeeDetailsPage() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel12 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		address = new javax.swing.JLabel();
		addressValue = new javax.swing.JLabel();
		jPanel31 = new javax.swing.JPanel();
		hoursRenderedLabel17 = new javax.swing.JLabel();
		grossSalaryComputationLabel17 = new javax.swing.JLabel();
		hourlyRateLabel17 = new javax.swing.JLabel();
		grossSalaryLabel17 = new javax.swing.JLabel();
		hourlyRateValue18 = new javax.swing.JLabel();
		grossSalaryValue17 = new javax.swing.JLabel();
		hoursRenderedValue = new javax.swing.JLabel();
		jPanel32 = new javax.swing.JPanel();
		netSalaryComputationLabel = new javax.swing.JLabel();
		sssDeductionsLabel = new javax.swing.JLabel();
		sssDeductionsValue = new javax.swing.JLabel();
		philhealthDeductionsLabel = new javax.swing.JLabel();
		philhealthDeductionsValue = new javax.swing.JLabel();
		totalDeductionsLabel = new javax.swing.JLabel();
		totalDeductionsValue = new javax.swing.JLabel();
		pagibigDeductionsLabel = new javax.swing.JLabel();
		pagibigDeductionsValue = new javax.swing.JLabel();
		grossSalaryLabel18 = new javax.swing.JLabel();
		grossSalaryValue18 = new javax.swing.JLabel();
		taxableSalaryLabel = new javax.swing.JLabel();
		taxableSalaryValue = new javax.swing.JLabel();
		withHoldingTaxLabel = new javax.swing.JLabel();
		withHoldingTaxValue = new javax.swing.JLabel();
		salaryAfterTaxLabel = new javax.swing.JLabel();
		salaryAfterTaxValue = new javax.swing.JLabel();
		totalAllowancesLabel1 = new javax.swing.JLabel();
		totalAllowancesValue1 = new javax.swing.JLabel();
		netSalaryLabel = new javax.swing.JLabel();
		netSalaryValue = new javax.swing.JLabel();
		jPanel33 = new javax.swing.JPanel();
		riceSubsidyLabel = new javax.swing.JLabel();
		riceSubsidyValue = new javax.swing.JLabel();
		phoneAllowanceLabel = new javax.swing.JLabel();
		phoneAllowanceValue = new javax.swing.JLabel();
		totalAllowanceLabel = new javax.swing.JLabel();
		totalAllowanceValue = new javax.swing.JLabel();
		allowancesLabel = new javax.swing.JLabel();
		clothingAllowanceLabel = new javax.swing.JLabel();
		clothingAllowanceValue = new javax.swing.JLabel();
		jPanel11 = new javax.swing.JPanel();
		firstName6 = new javax.swing.JLabel();
		firstNameValue6 = new javax.swing.JLabel();
		lastName6 = new javax.swing.JLabel();
		lastNameValue6 = new javax.swing.JLabel();
		birthday6 = new javax.swing.JLabel();
		birthdayValue6 = new javax.swing.JLabel();
		phoneNumber6 = new javax.swing.JLabel();
		phoneNumberValue6 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		status = new javax.swing.JLabel();
		statusValue = new javax.swing.JLabel();
		position = new javax.swing.JLabel();
		positionValue = new javax.swing.JLabel();
		immediateSupervisor = new javax.swing.JLabel();
		immediateSupervisorValue = new javax.swing.JLabel();
		hourlyRate = new javax.swing.JLabel();
		hourlyRateValue = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		sssNumber = new javax.swing.JLabel();
		sssNumberValue = new javax.swing.JLabel();
		philhealthNumber = new javax.swing.JLabel();
		philhealthNumberValue = new javax.swing.JLabel();
		pagibigNumber = new javax.swing.JLabel();
		pagibigNumberValue = new javax.swing.JLabel();
		tinNumber = new javax.swing.JLabel();
		tinNumberValue = new javax.swing.JLabel();
		monthDropdown = new javax.swing.JComboBox<>();
		computeButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));
		jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		address.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		address.setText("Address");

		addressValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		addressValue.setText(" ");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(15, 15, 15)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(address).addComponent(addressValue,
										javax.swing.GroupLayout.PREFERRED_SIZE, 785,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(address)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(addressValue)
						.addContainerGap(13, Short.MAX_VALUE)));

		jPanel31.setBackground(new java.awt.Color(255, 255, 255));
		jPanel31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		hoursRenderedLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		hoursRenderedLabel17.setText("Hours Rendered");

		grossSalaryComputationLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		grossSalaryComputationLabel17.setText("Gross Salary Computation");

		hourlyRateLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		hourlyRateLabel17.setText("Hourly Rate");

		grossSalaryLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		grossSalaryLabel17.setText("Gross Salary");

		hourlyRateValue18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		hourlyRateValue18.setText(" ");

		grossSalaryValue17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		grossSalaryValue17.setText(" ");

		hoursRenderedValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		hoursRenderedValue.setText(" ");

		javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
		jPanel31.setLayout(jPanel31Layout);
		jPanel31Layout.setHorizontalGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel31Layout.createSequentialGroup().addGap(42, 42, 42)
						.addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(hourlyRateLabel17).addComponent(hoursRenderedLabel17)
								.addComponent(grossSalaryLabel17))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(hourlyRateValue18, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(grossSalaryValue17, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(hoursRenderedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(45, 45, 45))
				.addGroup(jPanel31Layout.createSequentialGroup().addGap(14, 14, 14)
						.addComponent(grossSalaryComputationLabel17).addGap(0, 0, Short.MAX_VALUE)));
		jPanel31Layout
				.setVerticalGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
								.addGap(14, 14, 14).addComponent(grossSalaryComputationLabel17).addGap(28, 28, 28)
								.addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(hoursRenderedLabel17).addComponent(hoursRenderedValue))
								.addGap(18, 18, 18)
								.addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(hourlyRateLabel17).addComponent(hourlyRateValue18))
								.addGap(18, 18, 18)
								.addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(grossSalaryLabel17).addComponent(grossSalaryValue17))
								.addContainerGap(35, Short.MAX_VALUE)));

		jPanel32.setBackground(new java.awt.Color(255, 255, 255));
		jPanel32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		netSalaryComputationLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		netSalaryComputationLabel.setText("Net Salary Computation");

		sssDeductionsLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		sssDeductionsLabel.setText("SSS Deduction");

		sssDeductionsValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		sssDeductionsValue.setText(" ");

		philhealthDeductionsLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		philhealthDeductionsLabel.setText("PhilHealth Deduction");

		philhealthDeductionsValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		philhealthDeductionsValue.setText(" ");

		totalDeductionsLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		totalDeductionsLabel.setText("Total Deductions");

		totalDeductionsValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		totalDeductionsValue.setText(" ");

		pagibigDeductionsLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		pagibigDeductionsLabel.setText("Pag-ibig Deduction");

		pagibigDeductionsValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		pagibigDeductionsValue.setText(" ");

		grossSalaryLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		grossSalaryLabel18.setText("Gross Salary");

		grossSalaryValue18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		grossSalaryValue18.setText(" ");

		taxableSalaryLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		taxableSalaryLabel.setText("Taxable Salary");

		taxableSalaryValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		taxableSalaryValue.setText(" ");

		withHoldingTaxLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		withHoldingTaxLabel.setText("Withholding Tax");

		withHoldingTaxValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		withHoldingTaxValue.setText(" ");

		salaryAfterTaxLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		salaryAfterTaxLabel.setText("Salary After Tax");

		salaryAfterTaxValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		salaryAfterTaxValue.setText(" ");

		totalAllowancesLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		totalAllowancesLabel1.setText("Total Allowances");

		totalAllowancesValue1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		totalAllowancesValue1.setText(" ");

		netSalaryLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		netSalaryLabel.setText("Net Salary");

		netSalaryValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		netSalaryValue.setText(" ");

		javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
		jPanel32.setLayout(jPanel32Layout);
		jPanel32Layout.setHorizontalGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel32Layout.createSequentialGroup().addGap(15, 15, 15)
						.addComponent(netSalaryComputationLabel)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel32Layout.createSequentialGroup().addGap(48, 48, 48)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(philhealthDeductionsLabel).addComponent(sssDeductionsLabel)
								.addComponent(totalDeductionsLabel).addComponent(grossSalaryLabel18)
								.addComponent(taxableSalaryLabel).addComponent(withHoldingTaxLabel)
								.addComponent(salaryAfterTaxLabel).addComponent(netSalaryLabel)
								.addComponent(totalAllowancesLabel1).addComponent(pagibigDeductionsLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(netSalaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(totalAllowancesValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(salaryAfterTaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(withHoldingTaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(taxableSalaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(grossSalaryValue18, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(totalDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pagibigDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(philhealthDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE,
												132, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(sssDeductionsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(51, 51, 51)));
		jPanel32Layout.setVerticalGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel32Layout.createSequentialGroup().addGap(14, 14, 14)
						.addComponent(netSalaryComputationLabel).addGap(18, 18, 18)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(sssDeductionsLabel).addComponent(sssDeductionsValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(philhealthDeductionsLabel).addComponent(philhealthDeductionsValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(pagibigDeductionsLabel).addComponent(pagibigDeductionsValue))
						.addGap(18, 18, 18)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(totalDeductionsLabel).addComponent(totalDeductionsValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(grossSalaryLabel18).addComponent(grossSalaryValue18))
						.addGap(18, 18, 18)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(taxableSalaryLabel).addComponent(taxableSalaryValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(withHoldingTaxLabel).addComponent(withHoldingTaxValue))
						.addGap(18, 18, 18)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(salaryAfterTaxLabel).addComponent(salaryAfterTaxValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(totalAllowancesLabel1).addComponent(totalAllowancesValue1))
						.addGap(18, 18, 18)
						.addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(netSalaryLabel).addComponent(netSalaryValue))
						.addContainerGap(32, Short.MAX_VALUE)));

		jPanel33.setBackground(new java.awt.Color(255, 255, 255));
		jPanel33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		riceSubsidyLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		riceSubsidyLabel.setText("Rice Subsidy");

		riceSubsidyValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		riceSubsidyValue.setText(" ");

		phoneAllowanceLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		phoneAllowanceLabel.setText("Phone Allowance");

		phoneAllowanceValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		phoneAllowanceValue.setText(" ");

		totalAllowanceLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		totalAllowanceLabel.setText("Total Allowances");

		totalAllowanceValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		totalAllowanceValue.setText(" ");

		allowancesLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		allowancesLabel.setText("Allowances");

		clothingAllowanceLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		clothingAllowanceLabel.setText("Clothing Allowance");

		clothingAllowanceValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		clothingAllowanceValue.setText(" ");

		javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
		jPanel33.setLayout(jPanel33Layout);
		jPanel33Layout.setHorizontalGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel33Layout.createSequentialGroup().addGap(17, 17, 17).addComponent(allowancesLabel)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel33Layout.createSequentialGroup().addGap(37, 37, 37)
						.addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(phoneAllowanceLabel).addComponent(riceSubsidyLabel)
								.addComponent(totalAllowanceLabel).addComponent(clothingAllowanceLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
						.addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(phoneAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(riceSubsidyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(totalAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(clothingAllowanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(39, 39, 39)));
		jPanel33Layout.setVerticalGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel33Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(allowancesLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(riceSubsidyLabel).addComponent(riceSubsidyValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(phoneAllowanceLabel).addComponent(phoneAllowanceValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(clothingAllowanceLabel).addComponent(clothingAllowanceValue))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
						.addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(totalAllowanceLabel).addComponent(totalAllowanceValue))
						.addGap(18, 18, 18)));

		jPanel11.setBackground(new java.awt.Color(255, 255, 255));
		jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		jPanel11.setPreferredSize(new java.awt.Dimension(280, 299));

		firstName6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		firstName6.setText("First Name");

		firstNameValue6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		firstNameValue6.setText(" ");

		lastName6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		lastName6.setText("Last Name");

		lastNameValue6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		lastNameValue6.setText(" ");

		birthday6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		birthday6.setText("Birthday");

		birthdayValue6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		birthdayValue6.setText(" ");

		phoneNumber6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		phoneNumber6.setText("Phone Number");

		phoneNumberValue6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		phoneNumberValue6.setText(" ");

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(17, 17, 17).addGroup(jPanel11Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(phoneNumber6).addComponent(birthday6).addComponent(lastName6)
						.addComponent(firstName6)
						.addComponent(firstNameValue6, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
						.addComponent(lastNameValue6, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(birthdayValue6, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(phoneNumberValue6, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(73, Short.MAX_VALUE)));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(34, 34, 34).addComponent(firstName6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(firstNameValue6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lastName6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(lastNameValue6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(birthday6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(birthdayValue6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(phoneNumber6).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(phoneNumberValue6).addContainerGap(23, Short.MAX_VALUE)));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		jPanel3.setPreferredSize(new java.awt.Dimension(280, 277));

		status.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		status.setText("Status");

		statusValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		statusValue.setText(" ");

		position.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		position.setText("Position");

		positionValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		positionValue.setText(" ");

		immediateSupervisor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		immediateSupervisor.setText("Immediate Supervisor");

		immediateSupervisorValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		immediateSupervisorValue.setText(" ");

		hourlyRate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		hourlyRate.setText("Hourly Rate");

		hourlyRateValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		hourlyRateValue.setText(" ");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(hourlyRate).addComponent(immediateSupervisor).addComponent(position)
								.addComponent(status)
								.addComponent(statusValue, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
								.addComponent(positionValue, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(immediateSupervisorValue, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(hourlyRateValue, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(60, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(29, 29, 29).addComponent(status)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(statusValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(position)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(positionValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(immediateSupervisor)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(immediateSupervisorValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(hourlyRate)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(hourlyRateValue)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		jPanel4.setPreferredSize(new java.awt.Dimension(280, 277));

		sssNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		sssNumber.setText("SSS Number");

		sssNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		sssNumberValue.setText(" ");

		philhealthNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		philhealthNumber.setText("PhilHealth Number");

		philhealthNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		philhealthNumberValue.setText(" ");

		pagibigNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		pagibigNumber.setText("Pag-ibig Number");

		pagibigNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		pagibigNumberValue.setText(" ");

		tinNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		tinNumber.setText("TIN Number");

		tinNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		tinNumberValue.setText(" ");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(33, 33, 33).addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(tinNumber)
						.addComponent(pagibigNumber).addComponent(philhealthNumber).addComponent(sssNumber)
						.addComponent(sssNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
						.addComponent(philhealthNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(pagibigNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(tinNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(29, 29, 29).addComponent(sssNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(sssNumberValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(philhealthNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(philhealthNumberValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pagibigNumber).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pagibigNumberValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(tinNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(tinNumberValue)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel12Layout.createSequentialGroup().addContainerGap().addGroup(jPanel12Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel12Layout.createSequentialGroup()
										.addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 297,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 293,
												Short.MAX_VALUE))
								.addGroup(jPanel12Layout.createSequentialGroup()
										.addGroup(jPanel12Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel12Layout.createSequentialGroup().addContainerGap().addGroup(jPanel12Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(jPanel12Layout.createSequentialGroup()
								.addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jScrollPane1.setViewportView(jPanel12);

		monthDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March",
				"April", "May", "June", "July", "August", "September", "October", "November", "December" }));

		computeButton.setText("Compute");
		computeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				computeButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(41, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(monthDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(41, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(38, 38, 38)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(monthDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(35, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel address;
	private javax.swing.JLabel addressValue;
	private javax.swing.JLabel allowancesLabel;
	private javax.swing.JLabel birthday;
	private javax.swing.JLabel birthday1;
	private javax.swing.JLabel birthday2;
	private javax.swing.JLabel birthday3;
	private javax.swing.JLabel birthday4;
	private javax.swing.JLabel birthday5;
	private javax.swing.JLabel birthday6;
	private javax.swing.JLabel birthday7;
	private javax.swing.JLabel birthdayValue;
	private javax.swing.JLabel birthdayValue1;
	private javax.swing.JLabel birthdayValue2;
	private javax.swing.JLabel birthdayValue3;
	private javax.swing.JLabel birthdayValue4;
	private javax.swing.JLabel birthdayValue5;
	private javax.swing.JLabel birthdayValue6;
	private javax.swing.JLabel birthdayValue7;
	private javax.swing.JButton calculateSalaryButton;
	private javax.swing.JButton calculateSalaryButton1;
	private javax.swing.JButton calculateSalaryButton10;
	private javax.swing.JButton calculateSalaryButton11;
	private javax.swing.JButton calculateSalaryButton12;
	private javax.swing.JButton calculateSalaryButton13;
	private javax.swing.JButton calculateSalaryButton14;
	private javax.swing.JButton calculateSalaryButton15;
	private javax.swing.JButton calculateSalaryButton16;
	private javax.swing.JButton calculateSalaryButton2;
	private javax.swing.JButton calculateSalaryButton3;
	private javax.swing.JButton calculateSalaryButton4;
	private javax.swing.JButton calculateSalaryButton5;
	private javax.swing.JButton calculateSalaryButton6;
	private javax.swing.JButton calculateSalaryButton7;
	private javax.swing.JButton calculateSalaryButton8;
	private javax.swing.JButton calculateSalaryButton9;
	private javax.swing.JLabel clothingAllowanceLabel;
	private javax.swing.JLabel clothingAllowanceValue;
	private javax.swing.JButton computeButton;
	private javax.swing.JLabel firstName;
	private javax.swing.JLabel firstName1;
	private javax.swing.JLabel firstName2;
	private javax.swing.JLabel firstName3;
	private javax.swing.JLabel firstName4;
	private javax.swing.JLabel firstName5;
	private javax.swing.JLabel firstName6;
	private javax.swing.JLabel firstName7;
	private javax.swing.JLabel firstNameValue;
	private javax.swing.JLabel firstNameValue1;
	private javax.swing.JLabel firstNameValue2;
	private javax.swing.JLabel firstNameValue3;
	private javax.swing.JLabel firstNameValue4;
	private javax.swing.JLabel firstNameValue5;
	private javax.swing.JLabel firstNameValue6;
	private javax.swing.JLabel firstNameValue7;
	private javax.swing.JLabel grossSalaryComputationLabel;
	private javax.swing.JLabel grossSalaryComputationLabel1;
	private javax.swing.JLabel grossSalaryComputationLabel10;
	private javax.swing.JLabel grossSalaryComputationLabel11;
	private javax.swing.JLabel grossSalaryComputationLabel12;
	private javax.swing.JLabel grossSalaryComputationLabel13;
	private javax.swing.JLabel grossSalaryComputationLabel14;
	private javax.swing.JLabel grossSalaryComputationLabel15;
	private javax.swing.JLabel grossSalaryComputationLabel16;
	private javax.swing.JLabel grossSalaryComputationLabel17;
	private javax.swing.JLabel grossSalaryComputationLabel2;
	private javax.swing.JLabel grossSalaryComputationLabel3;
	private javax.swing.JLabel grossSalaryComputationLabel4;
	private javax.swing.JLabel grossSalaryComputationLabel5;
	private javax.swing.JLabel grossSalaryComputationLabel6;
	private javax.swing.JLabel grossSalaryComputationLabel7;
	private javax.swing.JLabel grossSalaryComputationLabel8;
	private javax.swing.JLabel grossSalaryComputationLabel9;
	private javax.swing.JLabel grossSalaryLabel;
	private javax.swing.JLabel grossSalaryLabel1;
	private javax.swing.JLabel grossSalaryLabel10;
	private javax.swing.JLabel grossSalaryLabel11;
	private javax.swing.JLabel grossSalaryLabel12;
	private javax.swing.JLabel grossSalaryLabel13;
	private javax.swing.JLabel grossSalaryLabel14;
	private javax.swing.JLabel grossSalaryLabel15;
	private javax.swing.JLabel grossSalaryLabel16;
	private javax.swing.JLabel grossSalaryLabel17;
	private javax.swing.JLabel grossSalaryLabel18;
	private javax.swing.JLabel grossSalaryLabel2;
	private javax.swing.JLabel grossSalaryLabel3;
	private javax.swing.JLabel grossSalaryLabel4;
	private javax.swing.JLabel grossSalaryLabel5;
	private javax.swing.JLabel grossSalaryLabel6;
	private javax.swing.JLabel grossSalaryLabel7;
	private javax.swing.JLabel grossSalaryLabel8;
	private javax.swing.JLabel grossSalaryLabel9;
	private javax.swing.JLabel grossSalaryValue;
	private javax.swing.JLabel grossSalaryValue1;
	private javax.swing.JLabel grossSalaryValue10;
	private javax.swing.JLabel grossSalaryValue11;
	private javax.swing.JLabel grossSalaryValue12;
	private javax.swing.JLabel grossSalaryValue13;
	private javax.swing.JLabel grossSalaryValue14;
	private javax.swing.JLabel grossSalaryValue15;
	private javax.swing.JLabel grossSalaryValue16;
	private javax.swing.JLabel grossSalaryValue17;
	private javax.swing.JLabel grossSalaryValue18;
	private javax.swing.JLabel grossSalaryValue2;
	private javax.swing.JLabel grossSalaryValue3;
	private javax.swing.JLabel grossSalaryValue4;
	private javax.swing.JLabel grossSalaryValue5;
	private javax.swing.JLabel grossSalaryValue6;
	private javax.swing.JLabel grossSalaryValue7;
	private javax.swing.JLabel grossSalaryValue8;
	private javax.swing.JLabel grossSalaryValue9;
	private javax.swing.JLabel hourlyRate;
	private javax.swing.JLabel hourlyRateLabel;
	private javax.swing.JLabel hourlyRateLabel1;
	private javax.swing.JLabel hourlyRateLabel10;
	private javax.swing.JLabel hourlyRateLabel11;
	private javax.swing.JLabel hourlyRateLabel12;
	private javax.swing.JLabel hourlyRateLabel13;
	private javax.swing.JLabel hourlyRateLabel14;
	private javax.swing.JLabel hourlyRateLabel15;
	private javax.swing.JLabel hourlyRateLabel16;
	private javax.swing.JLabel hourlyRateLabel17;
	private javax.swing.JLabel hourlyRateLabel2;
	private javax.swing.JLabel hourlyRateLabel3;
	private javax.swing.JLabel hourlyRateLabel4;
	private javax.swing.JLabel hourlyRateLabel5;
	private javax.swing.JLabel hourlyRateLabel6;
	private javax.swing.JLabel hourlyRateLabel7;
	private javax.swing.JLabel hourlyRateLabel8;
	private javax.swing.JLabel hourlyRateLabel9;
	private javax.swing.JLabel hourlyRateValue;
	private javax.swing.JLabel hourlyRateValue1;
	private javax.swing.JLabel hourlyRateValue10;
	private javax.swing.JLabel hourlyRateValue11;
	private javax.swing.JLabel hourlyRateValue12;
	private javax.swing.JLabel hourlyRateValue13;
	private javax.swing.JLabel hourlyRateValue14;
	private javax.swing.JLabel hourlyRateValue15;
	private javax.swing.JLabel hourlyRateValue16;
	private javax.swing.JLabel hourlyRateValue17;
	private javax.swing.JLabel hourlyRateValue18;
	private javax.swing.JLabel hourlyRateValue2;
	private javax.swing.JLabel hourlyRateValue3;
	private javax.swing.JLabel hourlyRateValue4;
	private javax.swing.JLabel hourlyRateValue5;
	private javax.swing.JLabel hourlyRateValue6;
	private javax.swing.JLabel hourlyRateValue7;
	private javax.swing.JLabel hourlyRateValue8;
	private javax.swing.JLabel hourlyRateValue9;
	private javax.swing.JTextField hoursRenderedField;
	private javax.swing.JTextField hoursRenderedField1;
	private javax.swing.JTextField hoursRenderedField10;
	private javax.swing.JTextField hoursRenderedField11;
	private javax.swing.JTextField hoursRenderedField12;
	private javax.swing.JTextField hoursRenderedField13;
	private javax.swing.JTextField hoursRenderedField14;
	private javax.swing.JTextField hoursRenderedField15;
	private javax.swing.JTextField hoursRenderedField16;
	private javax.swing.JTextField hoursRenderedField2;
	private javax.swing.JTextField hoursRenderedField3;
	private javax.swing.JTextField hoursRenderedField4;
	private javax.swing.JTextField hoursRenderedField5;
	private javax.swing.JTextField hoursRenderedField6;
	private javax.swing.JTextField hoursRenderedField7;
	private javax.swing.JTextField hoursRenderedField8;
	private javax.swing.JTextField hoursRenderedField9;
	private javax.swing.JLabel hoursRenderedLabel;
	private javax.swing.JLabel hoursRenderedLabel1;
	private javax.swing.JLabel hoursRenderedLabel10;
	private javax.swing.JLabel hoursRenderedLabel11;
	private javax.swing.JLabel hoursRenderedLabel12;
	private javax.swing.JLabel hoursRenderedLabel13;
	private javax.swing.JLabel hoursRenderedLabel14;
	private javax.swing.JLabel hoursRenderedLabel15;
	private javax.swing.JLabel hoursRenderedLabel16;
	private javax.swing.JLabel hoursRenderedLabel17;
	private javax.swing.JLabel hoursRenderedLabel2;
	private javax.swing.JLabel hoursRenderedLabel3;
	private javax.swing.JLabel hoursRenderedLabel4;
	private javax.swing.JLabel hoursRenderedLabel5;
	private javax.swing.JLabel hoursRenderedLabel6;
	private javax.swing.JLabel hoursRenderedLabel7;
	private javax.swing.JLabel hoursRenderedLabel8;
	private javax.swing.JLabel hoursRenderedLabel9;
	private javax.swing.JLabel hoursRenderedValue;
	private javax.swing.JLabel immediateSupervisor;
	private javax.swing.JLabel immediateSupervisorValue;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel19;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel20;
	private javax.swing.JPanel jPanel21;
	private javax.swing.JPanel jPanel22;
	private javax.swing.JPanel jPanel23;
	private javax.swing.JPanel jPanel24;
	private javax.swing.JPanel jPanel25;
	private javax.swing.JPanel jPanel26;
	private javax.swing.JPanel jPanel27;
	private javax.swing.JPanel jPanel28;
	private javax.swing.JPanel jPanel29;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel30;
	private javax.swing.JPanel jPanel31;
	private javax.swing.JPanel jPanel32;
	private javax.swing.JPanel jPanel33;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lastName;
	private javax.swing.JLabel lastName1;
	private javax.swing.JLabel lastName2;
	private javax.swing.JLabel lastName3;
	private javax.swing.JLabel lastName4;
	private javax.swing.JLabel lastName5;
	private javax.swing.JLabel lastName6;
	private javax.swing.JLabel lastName7;
	private javax.swing.JLabel lastNameValue;
	private javax.swing.JLabel lastNameValue1;
	private javax.swing.JLabel lastNameValue2;
	private javax.swing.JLabel lastNameValue3;
	private javax.swing.JLabel lastNameValue4;
	private javax.swing.JLabel lastNameValue5;
	private javax.swing.JLabel lastNameValue6;
	private javax.swing.JLabel lastNameValue7;
	private javax.swing.JComboBox<String> monthDropdown;
	private javax.swing.JLabel netSalaryComputationLabel;
	private javax.swing.JLabel netSalaryLabel;
	private javax.swing.JLabel netSalaryValue;
	private javax.swing.JLabel pagibigDeductionsLabel;
	private javax.swing.JLabel pagibigDeductionsValue;
	private javax.swing.JLabel pagibigNumber;
	private javax.swing.JLabel pagibigNumberValue;
	private javax.swing.JLabel philhealthDeductionsLabel;
	private javax.swing.JLabel philhealthDeductionsValue;
	private javax.swing.JLabel philhealthNumber;
	private javax.swing.JLabel philhealthNumberValue;
	private javax.swing.JLabel phoneAllowanceLabel;
	private javax.swing.JLabel phoneAllowanceValue;
	private javax.swing.JLabel phoneNumber;
	private javax.swing.JLabel phoneNumber1;
	private javax.swing.JLabel phoneNumber2;
	private javax.swing.JLabel phoneNumber3;
	private javax.swing.JLabel phoneNumber4;
	private javax.swing.JLabel phoneNumber5;
	private javax.swing.JLabel phoneNumber6;
	private javax.swing.JLabel phoneNumber7;
	private javax.swing.JLabel phoneNumberValue;
	private javax.swing.JLabel phoneNumberValue1;
	private javax.swing.JLabel phoneNumberValue2;
	private javax.swing.JLabel phoneNumberValue3;
	private javax.swing.JLabel phoneNumberValue4;
	private javax.swing.JLabel phoneNumberValue5;
	private javax.swing.JLabel phoneNumberValue6;
	private javax.swing.JLabel phoneNumberValue7;
	private javax.swing.JLabel position;
	private javax.swing.JLabel positionValue;
	private javax.swing.JLabel riceSubsidyLabel;
	private javax.swing.JLabel riceSubsidyValue;
	private javax.swing.JLabel salaryAfterTaxLabel;
	private javax.swing.JLabel salaryAfterTaxValue;
	private javax.swing.JLabel sssDeductionsLabel;
	private javax.swing.JLabel sssDeductionsValue;
	private javax.swing.JLabel sssNumber;
	private javax.swing.JLabel sssNumberValue;
	private javax.swing.JLabel status;
	private javax.swing.JLabel statusValue;
	private javax.swing.JLabel taxableSalaryLabel;
	private javax.swing.JLabel taxableSalaryValue;
	private javax.swing.JLabel tinNumber;
	private javax.swing.JLabel tinNumberValue;
	private javax.swing.JLabel totalAllowanceLabel;
	private javax.swing.JLabel totalAllowanceValue;
	private javax.swing.JLabel totalAllowancesLabel1;
	private javax.swing.JLabel totalAllowancesValue1;
	private javax.swing.JLabel totalDeductionsLabel;
	private javax.swing.JLabel totalDeductionsValue;
	private javax.swing.JLabel withHoldingTaxLabel;
	private javax.swing.JLabel withHoldingTaxValue;
	// End of variables declaration

}
